import { Inter } from 'next/font/google'
import { redirect } from 'next/navigation'
import React from 'react'
import '../globals.css'

import { cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Faça seu login - DocGuard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const token = cookies().get('doc-guard.token')?.value

  if (token) {
    return redirect('/')
  }

  return (
    <html lang="pt-BR">
      <body className={inter.className}>{children} </body>
    </html>
  )
}
