import { Inter } from 'next/font/google'

import React from 'react'
import 'react-toastify/dist/ReactToastify.css'
import './globals.css'
import { Providers } from '@/components/providers'

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" className={inter.className}>
      <body>
        <div className="">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  )
}
